### ISSUE TITLE
Documentation link on webpage is broken

### ISSUE THREAD

**Issue by funsim** [OptimoJoe/Optizelle#44]
The landing page of Optizelle points to a dead documentation links:

http://www.optimojoe.com/uploads/reports/Optizelle-1.1.2-a4.pdf

and 

http://www.optimojoe.com/uploads/reports/Optizelle-1.1.2-letter.pdf

**Comment by josyoun** [comment]
Drat!  Basically, I migrated to a new web host and it broke a bunch of links.  Hopefully, this is all fixed now.  Thanks for the heads up!

**Comment by funsim** [comment]
Works, thanks!
