### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by pstojanov** [OptimoJoe/Optizelle#55]
Dear Authors, 

Seems like the links to the documentation pdfs are broken. Could you possibly re-upload them? 

Thanks a lot!
-Petar

**Comment by josyoun** [comment]
Hi Petar.  Thanks for letting me know!  It looks like I had some old links on the website, but the ones on Github were accurate.  Where did you see the dead link?  Theoretically, the ones on the website should be fixed now, but it may take a few minutes for the website caching to properly kick in at your location.

**Comment by josyoun** [comment]
As far as I know, our links should be good.  Closing.
